"""Generated by scripts/generate_lead_contract.py from db/contracts/lead-capture.v1.json. Do not edit."""

import json
from typing import Any, Final

CONTRACT: Final[dict[str, Any]] = json.loads(
    r"""{
  "$comment": "Canonical lead capture contract. Voice (Python) and WhatsApp/web (TypeScript) both validate and normalize lead fields from this file, and both commit through the same platform.* PostgreSQL functions. Generated mirrors: packages/ts/crm/src/lead-capture-contract.generated.ts and packages/py/oron-agent/src/oron_agent/lead_capture_contract.py (scripts/generate_lead_contract.py). Patterns avoid \\s, \\d, \\b and \\w because JavaScript and Python define them differently; lengths are UTF-16 code units because that is what JavaScript measures.",
  "contractVersion": "1.0",
  "enums": {
    "fieldTypes": [
      "text",
      "number",
      "currency",
      "date",
      "email",
      "phone",
      "boolean",
      "choice"
    ],
    "fieldStates": [
      "known",
      "unknown",
      "declined",
      "not_applicable"
    ],
    "confirmations": [
      "unconfirmed",
      "customer_confirmed",
      "human_verified"
    ],
    "leadStatuses": [
      "new",
      "collecting",
      "ready_for_review",
      "qualified",
      "disqualified",
      "converted",
      "archived"
    ],
    "sourceChannels": [
      "voice",
      "whatsapp",
      "manual",
      "api"
    ],
    "recordedBy": [
      "agent",
      "human",
      "system"
    ],
    "operations": [
      "lead.create",
      "lead.save_fields",
      "lead.finalize",
      "lead.request_follow_up",
      "lead.update"
    ],
    "capabilities": [
      "lead.read",
      "lead.write",
      "lead.finalize",
      "lead.follow_up"
    ]
  },
  "limits": {
    "schemaFields": 40,
    "observationsPerCall": 40,
    "rawValueLength": 1200,
    "defaultTextLength": 400,
    "maxLengthCeiling": 1200,
    "labelLength": 120,
    "descriptionLength": 400,
    "choices": 40,
    "choiceLength": 120,
    "sourceReferenceLength": 200,
    "operationKeyMin": 8,
    "operationKeyMax": 200,
    "summaryLength": 4000,
    "followUpNoteLength": 1000,
    "interestKeyLength": 120,
    "absoluteNumber": 1000000000000000,
    "dateYearMin": 1900,
    "dateYearMax": 2200
  },
  "patterns": {
    "trimmable": "^[\\t\\n\\u000b\\f\\r \\u00a0\\u1680\\u2000-\\u200a\\u2028\\u2029\\u202f\\u205f\\u3000\\ufeff]+|[\\t\\n\\u000b\\f\\r \\u00a0\\u1680\\u2000-\\u200a\\u2028\\u2029\\u202f\\u205f\\u3000\\ufeff]+$",
    "fieldKey": "^[a-z][a-z0-9_]{0,62}$",
    "email": "^[^@\\t\\n\\u000b\\f\\r \\u00a0\\u1680\\u2000-\\u200a\\u2028\\u2029\\u202f\\u205f\\u3000\\ufeff]{1,64}@[a-z0-9.\\-]{1,190}\\.[a-z]{2,24}$",
    "phoneSeparators": "[\\t\\n\\u000b\\f\\r \\u00a0\\u1680\\u2000-\\u200a\\u2028\\u2029\\u202f\\u205f\\u3000\\ufeff()\\u2010-\\u2015.\\-]",
    "nonDigit": "[^0-9]",
    "e164": "^\\+[1-9][0-9]{7,14}$",
    "numberSpacing": "[\\t\\n\\u000b\\f\\r \\u00a0\\u1680\\u2000-\\u200a\\u2028\\u2029\\u202f\\u205f\\u3000\\ufeff]",
    "thousandsComma": ",(?=[0-9]{3}(?![0-9A-Za-z_]))",
    "decimalNumber": "^[+\\-]?(?:[0-9]+(?:\\.[0-9]*)?|\\.[0-9]+)(?:[eE][+\\-]?[0-9]+)?$",
    "isoDate": "^([0-9]{4})-([0-9]{2})-([0-9]{2})$",
    "isoInstant": "^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}(?::[0-9]{2}(?:\\.[0-9]{1,9})?)?(?:Z|[+\\-][0-9]{2}:[0-9]{2})$",
    "currency": "^[A-Z]{3}$"
  },
  "phoneRegions": {
    "IL": {
      "countryCode": "972",
      "national": "^0([2-9][0-9]{7,8})$"
    }
  },
  "booleanTokens": {
    "true": [
      "true",
      "yes",
      "y",
      "1",
      "כן"
    ],
    "false": [
      "false",
      "no",
      "n",
      "0",
      "לא"
    ]
  },
  "rounding": {
    "currencyDecimals": 2,
    "mode": "half_up_on_exact_binary_value"
  },
  "errorCodes": [
    "invalid_schema",
    "unknown_field",
    "unsupported_state",
    "unsupported_confirmation",
    "invalid_observed_at",
    "reference_too_long",
    "content_without_known",
    "blank_known",
    "value_too_long",
    "text_too_long",
    "invalid_choice",
    "invalid_email",
    "invalid_phone",
    "invalid_boolean",
    "invalid_number",
    "number_too_large",
    "below_minimum",
    "above_maximum",
    "currency_required",
    "negative_amount",
    "invalid_date_format",
    "invalid_calendar_date",
    "date_out_of_range"
  ],
  "tools": {
    "capabilityImplies": {
      "lead.read": [
        "lead.write",
        "lead.finalize",
        "lead.follow_up"
      ]
    },
    "maxObservationsPerCall": 20,
    "observationItem": {
      "key": "Which reviewed field this observation belongs to.",
      "state": "known when the customer gave a value, declined when they refused, not_applicable when the question does not apply, unknown otherwise. Missing is not zero and a refusal is not consent.",
      "value": "The customer's own words, only when state is known. Never a guess, a suggestion of yours, or a value the customer has not confirmed.",
      "currency": "ISO 4217 code, required with a monetary amount.",
      "confirmed": "True only when the customer explicitly confirmed the value.",
      "sourceReference": "Identifier of the accepted message or turn this value came from."
    },
    "definitions": [
      {
        "name": "lead_read_state",
        "capability": "lead.read",
        "mutating": false,
        "description": "Read what has already been collected for this customer's current enquiry, including which required fields are still missing. Use it before asking, so a completed question is not repeated.",
        "arguments": {}
      },
      {
        "name": "lead_save_fields",
        "capability": "lead.write",
        "mutating": true,
        "description": "Save information the customer actually gave. Only say it is saved after this returns a receipt.",
        "arguments": {}
      },
      {
        "name": "lead_finalize_collection",
        "capability": "lead.finalize",
        "mutating": true,
        "description": "Hand the completed enquiry to a person for review. This does not qualify the lead and does not book anything.",
        "arguments": {
          "summary": {
            "type": "string",
            "maxLength": 4000,
            "required": true,
            "description": "What the customer asked for, in their own terms."
          },
          "nextAction": {
            "type": "string",
            "maxLength": 1000,
            "required": false
          }
        }
      },
      {
        "name": "lead_request_follow_up",
        "capability": "lead.follow_up",
        "mutating": true,
        "description": "Record that a person should follow up, with what the customer asked for.",
        "arguments": {
          "note": {
            "type": "string",
            "maxLength": 1000,
            "required": true
          },
          "dueAt": {
            "type": "string",
            "required": false,
            "description": "ISO timestamp, only when the customer named a specific time."
          }
        }
      }
    ]
  },
  "parity": {
    "schema": [
      {
        "key": "name",
        "label": "Preferred name",
        "type": "text",
        "required": true,
        "maxLength": 12
      },
      {
        "key": "company",
        "label": "Company",
        "type": "text",
        "required": true
      },
      {
        "key": "service",
        "label": "Service",
        "type": "choice",
        "required": true,
        "choices": [
          "CRM",
          "ERP",
          "Consulting"
        ]
      },
      {
        "key": "users",
        "label": "Users",
        "type": "number",
        "required": false,
        "minimum": 1,
        "maximum": 100000
      },
      {
        "key": "budget",
        "label": "Budget",
        "type": "currency",
        "required": false,
        "minimum": 0
      },
      {
        "key": "start_date",
        "label": "Start",
        "type": "date",
        "required": false
      },
      {
        "key": "email",
        "label": "Email",
        "type": "email",
        "required": false
      },
      {
        "key": "phone",
        "label": "Phone",
        "type": "phone",
        "required": false
      },
      {
        "key": "newsletter",
        "label": "Newsletter",
        "type": "boolean",
        "required": false
      }
    ],
    "normalization": [
      {
        "name": "text is trimmed and kept verbatim",
        "observation": {
          "key": "name",
          "state": "known",
          "value": "  רוני  "
        },
        "expect": {
          "state": "known",
          "rawValue": "רוני",
          "normalizedValue": "רוני",
          "currency": null,
          "confirmation": "unconfirmed"
        }
      },
      {
        "name": "text over its schema limit",
        "observation": {
          "key": "name",
          "state": "known",
          "value": "abcdefghijklm"
        },
        "error": "text_too_long"
      },
      {
        "name": "text limit counts UTF-16 units",
        "observation": {
          "key": "name",
          "state": "known",
          "value": "😀😀😀😀😀😀😀"
        },
        "error": "text_too_long"
      },
      {
        "name": "blank known value",
        "observation": {
          "key": "company",
          "state": "known",
          "value": "   "
        },
        "error": "blank_known"
      },
      {
        "name": "unknown may not carry content",
        "observation": {
          "key": "company",
          "state": "unknown",
          "value": "Acme"
        },
        "error": "content_without_known"
      },
      {
        "name": "declined is stored without content",
        "observation": {
          "key": "company",
          "state": "declined"
        },
        "expect": {
          "state": "declined",
          "rawValue": null,
          "normalizedValue": null,
          "currency": null,
          "confirmation": "unconfirmed"
        }
      },
      {
        "name": "not applicable is stored without content",
        "observation": {
          "key": "users",
          "state": "not_applicable",
          "value": "  "
        },
        "expect": {
          "state": "not_applicable",
          "rawValue": null,
          "normalizedValue": null,
          "currency": null,
          "confirmation": "unconfirmed"
        }
      },
      {
        "name": "field outside the reviewed schema",
        "observation": {
          "key": "national_id",
          "state": "known",
          "value": "123"
        },
        "error": "unknown_field"
      },
      {
        "name": "unsupported state",
        "observation": {
          "key": "company",
          "state": "maybe",
          "value": "Acme"
        },
        "error": "unsupported_state"
      },
      {
        "name": "unsupported confirmation",
        "observation": {
          "key": "company",
          "state": "known",
          "value": "Acme",
          "confirmation": "certain"
        },
        "error": "unsupported_confirmation"
      },
      {
        "name": "confirmation passes through",
        "observation": {
          "key": "company",
          "state": "known",
          "value": "Acme",
          "confirmation": "customer_confirmed"
        },
        "expect": {
          "state": "known",
          "rawValue": "Acme",
          "normalizedValue": "Acme",
          "currency": null,
          "confirmation": "customer_confirmed"
        }
      },
      {
        "name": "choice matches case-insensitively to the canonical spelling",
        "observation": {
          "key": "service",
          "state": "known",
          "value": "crm"
        },
        "expect": {
          "state": "known",
          "rawValue": "crm",
          "normalizedValue": "CRM",
          "currency": null,
          "confirmation": "unconfirmed"
        }
      },
      {
        "name": "choice outside the list",
        "observation": {
          "key": "service",
          "state": "known",
          "value": "Hosting"
        },
        "error": "invalid_choice"
      },
      {
        "name": "thousands comma",
        "observation": {
          "key": "users",
          "state": "known",
          "value": "1,500"
        },
        "expect": {
          "state": "known",
          "rawValue": "1,500",
          "normalizedValue": "1500",
          "currency": null,
          "confirmation": "unconfirmed"
        }
      },
      {
        "name": "decimal comma",
        "observation": {
          "key": "users",
          "state": "known",
          "value": "12,5"
        },
        "expect": {
          "state": "known",
          "rawValue": "12,5",
          "normalizedValue": "12.5",
          "currency": null,
          "confirmation": "unconfirmed"
        }
      },
      {
        "name": "non-breaking space grouping",
        "observation": {
          "key": "users",
          "state": "known",
          "value": "1 200"
        },
        "expect": {
          "state": "known",
          "rawValue": "1 200",
          "normalizedValue": "1200",
          "currency": null,
          "confirmation": "unconfirmed"
        }
      },
      {
        "name": "trailing decimal point",
        "observation": {
          "key": "users",
          "state": "known",
          "value": "5."
        },
        "expect": {
          "state": "known",
          "rawValue": "5.",
          "normalizedValue": "5",
          "currency": null,
          "confirmation": "unconfirmed"
        }
      },
      {
        "name": "fractional number",
        "observation": {
          "key": "users",
          "state": "known",
          "value": "1.5"
        },
        "expect": {
          "state": "known",
          "rawValue": "1.5",
          "normalizedValue": "1.5",
          "currency": null,
          "confirmation": "unconfirmed"
        }
      },
      {
        "name": "hexadecimal is not a head count",
        "observation": {
          "key": "users",
          "state": "known",
          "value": "0x10"
        },
        "error": "invalid_number"
      },
      {
        "name": "digit grouping underscores are not accepted",
        "observation": {
          "key": "users",
          "state": "known",
          "value": "1_000"
        },
        "error": "invalid_number"
      },
      {
        "name": "words are not numbers",
        "observation": {
          "key": "users",
          "state": "known",
          "value": "about twenty"
        },
        "error": "invalid_number"
      },
      {
        "name": "below the schema minimum",
        "observation": {
          "key": "users",
          "state": "known",
          "value": "0"
        },
        "error": "below_minimum"
      },
      {
        "name": "above the schema maximum",
        "observation": {
          "key": "users",
          "state": "known",
          "value": "250000"
        },
        "error": "above_maximum"
      },
      {
        "name": "absurd magnitude",
        "observation": {
          "key": "budget",
          "state": "known",
          "value": "1e21",
          "currency": "USD"
        },
        "error": "number_too_large"
      },
      {
        "name": "amount with currency",
        "observation": {
          "key": "budget",
          "state": "known",
          "value": "50,000",
          "currency": "ils"
        },
        "expect": {
          "state": "known",
          "rawValue": "50,000",
          "normalizedValue": "50000.00",
          "currency": "ILS",
          "confirmation": "unconfirmed"
        }
      },
      {
        "name": "amount rounds half up",
        "observation": {
          "key": "budget",
          "state": "known",
          "value": "0.125",
          "currency": "USD"
        },
        "expect": {
          "state": "known",
          "rawValue": "0.125",
          "normalizedValue": "0.13",
          "currency": "USD",
          "confirmation": "unconfirmed"
        }
      },
      {
        "name": "amount in exponent form",
        "observation": {
          "key": "budget",
          "state": "known",
          "value": "1e3",
          "currency": "EUR"
        },
        "expect": {
          "state": "known",
          "rawValue": "1e3",
          "normalizedValue": "1000.00",
          "currency": "EUR",
          "confirmation": "unconfirmed"
        }
      },
      {
        "name": "amount without a currency is not guessed",
        "observation": {
          "key": "budget",
          "state": "known",
          "value": "5000"
        },
        "error": "currency_required"
      },
      {
        "name": "negative amount",
        "observation": {
          "key": "budget",
          "state": "known",
          "value": "-5",
          "currency": "USD"
        },
        "error": "negative_amount"
      },
      {
        "name": "exact calendar date",
        "observation": {
          "key": "start_date",
          "state": "known",
          "value": "2026-10-01"
        },
        "expect": {
          "state": "known",
          "rawValue": "2026-10-01",
          "normalizedValue": "2026-10-01",
          "currency": null,
          "confirmation": "unconfirmed"
        }
      },
      {
        "name": "impossible calendar date",
        "observation": {
          "key": "start_date",
          "state": "known",
          "value": "2026-02-30"
        },
        "error": "invalid_calendar_date"
      },
      {
        "name": "ambiguous local date format",
        "observation": {
          "key": "start_date",
          "state": "known",
          "value": "01/10/2026"
        },
        "error": "invalid_date_format"
      },
      {
        "name": "date outside the supported range",
        "observation": {
          "key": "start_date",
          "state": "known",
          "value": "1800-01-01"
        },
        "error": "date_out_of_range"
      },
      {
        "name": "leap day",
        "observation": {
          "key": "start_date",
          "state": "known",
          "value": "2028-02-29"
        },
        "expect": {
          "state": "known",
          "rawValue": "2028-02-29",
          "normalizedValue": "2028-02-29",
          "currency": null,
          "confirmation": "unconfirmed"
        }
      },
      {
        "name": "email is lowercased",
        "observation": {
          "key": "email",
          "state": "known",
          "value": "Roni@Example.CO.IL"
        },
        "expect": {
          "state": "known",
          "rawValue": "Roni@Example.CO.IL",
          "normalizedValue": "roni@example.co.il",
          "currency": null,
          "confirmation": "unconfirmed"
        }
      },
      {
        "name": "incomplete email",
        "observation": {
          "key": "email",
          "state": "known",
          "value": "roni@"
        },
        "error": "invalid_email"
      },
      {
        "name": "international phone with separators",
        "observation": {
          "key": "phone",
          "state": "known",
          "value": "+972 50-123-4567"
        },
        "expect": {
          "state": "known",
          "rawValue": "+972 50-123-4567",
          "normalizedValue": "+972501234567",
          "currency": null,
          "confirmation": "unconfirmed"
        }
      },
      {
        "name": "local phone with an approved region",
        "observation": {
          "key": "phone",
          "state": "known",
          "value": "050-123-4567"
        },
        "options": {
          "phoneRegion": "IL"
        },
        "expect": {
          "state": "known",
          "rawValue": "050-123-4567",
          "normalizedValue": "+972501234567",
          "currency": null,
          "confirmation": "unconfirmed"
        }
      },
      {
        "name": "local phone without a region is not guessed",
        "observation": {
          "key": "phone",
          "state": "known",
          "value": "050-123-4567"
        },
        "error": "invalid_phone"
      },
      {
        "name": "too short to be a phone",
        "observation": {
          "key": "phone",
          "state": "known",
          "value": "12345"
        },
        "options": {
          "phoneRegion": "IL"
        },
        "error": "invalid_phone"
      },
      {
        "name": "Hebrew yes",
        "observation": {
          "key": "newsletter",
          "state": "known",
          "value": "כן"
        },
        "expect": {
          "state": "known",
          "rawValue": "כן",
          "normalizedValue": "true",
          "currency": null,
          "confirmation": "unconfirmed"
        }
      },
      {
        "name": "English no",
        "observation": {
          "key": "newsletter",
          "state": "known",
          "value": "No"
        },
        "expect": {
          "state": "known",
          "rawValue": "No",
          "normalizedValue": "false",
          "currency": null,
          "confirmation": "unconfirmed"
        }
      },
      {
        "name": "hedged answer is not a boolean",
        "observation": {
          "key": "newsletter",
          "state": "known",
          "value": "sometimes"
        },
        "error": "invalid_boolean"
      },
      {
        "name": "observation time must be an instant",
        "observation": {
          "key": "company",
          "state": "known",
          "value": "Acme",
          "observedAt": "yesterday"
        },
        "error": "invalid_observed_at"
      },
      {
        "name": "observation time is kept",
        "observation": {
          "key": "company",
          "state": "known",
          "value": "Acme",
          "observedAt": "2026-09-19T10:00:00.000Z",
          "sourceReferenceId": "  msg-1 "
        },
        "expect": {
          "state": "known",
          "rawValue": "Acme",
          "normalizedValue": "Acme",
          "currency": null,
          "confirmation": "unconfirmed",
          "observedAt": "2026-09-19T10:00:00.000Z",
          "sourceReferenceId": "msg-1"
        }
      },
      {
        "name": "source reference is bounded",
        "observation": {
          "key": "company",
          "state": "known",
          "value": "Acme",
          "sourceReferenceId": "rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
        },
        "error": "reference_too_long"
      }
    ],
    "completeness": [
      {
        "name": "declined required field is resolved, not missing",
        "current": [
          {
            "key": "name",
            "state": "known"
          },
          {
            "key": "company",
            "state": "declined"
          }
        ],
        "expect": {
          "required": [
            "name",
            "company",
            "service"
          ],
          "satisfied": [
            "name",
            "company"
          ],
          "missing": [
            "service"
          ],
          "declined": [
            "company"
          ],
          "complete": false
        }
      },
      {
        "name": "unknown is still missing",
        "current": [
          {
            "key": "name",
            "state": "known"
          },
          {
            "key": "company",
            "state": "unknown"
          },
          {
            "key": "service",
            "state": "known"
          }
        ],
        "expect": {
          "required": [
            "name",
            "company",
            "service"
          ],
          "satisfied": [
            "name",
            "service"
          ],
          "missing": [
            "company"
          ],
          "declined": [],
          "complete": false
        }
      },
      {
        "name": "optional fields never block completeness",
        "current": [
          {
            "key": "name",
            "state": "known"
          },
          {
            "key": "company",
            "state": "known"
          },
          {
            "key": "service",
            "state": "not_applicable"
          }
        ],
        "expect": {
          "required": [
            "name",
            "company",
            "service"
          ],
          "satisfied": [
            "name",
            "company",
            "service"
          ],
          "missing": [],
          "declined": [
            "service"
          ],
          "complete": true
        }
      }
    ],
    "schemas": [
      {
        "name": "duplicate keys",
        "definition": [
          {
            "key": "a",
            "label": "A",
            "type": "text",
            "required": true
          },
          {
            "key": "a",
            "label": "A again",
            "type": "text",
            "required": false
          }
        ],
        "error": "invalid_schema"
      },
      {
        "name": "choice without choices",
        "definition": [
          {
            "key": "tier",
            "label": "Tier",
            "type": "choice",
            "required": true
          }
        ],
        "error": "invalid_schema"
      },
      {
        "name": "required must be explicit",
        "definition": [
          {
            "key": "a",
            "label": "A",
            "type": "text"
          }
        ],
        "error": "invalid_schema"
      },
      {
        "name": "bad key shape",
        "definition": [
          {
            "key": "Bad Key",
            "label": "A",
            "type": "text",
            "required": true
          }
        ],
        "error": "invalid_schema"
      },
      {
        "name": "minimum above maximum",
        "definition": [
          {
            "key": "n",
            "label": "N",
            "type": "number",
            "required": false,
            "minimum": 5,
            "maximum": 1
          }
        ],
        "error": "invalid_schema"
      },
      {
        "name": "empty schema",
        "definition": [],
        "error": "invalid_schema"
      },
      {
        "name": "wrapped schema object",
        "definition": {
          "fields": [
            {
              "key": "seats",
              "label": "Seats",
              "type": "number",
              "required": true,
              "minimum": 1
            }
          ]
        },
        "expectKeys": [
          "seats"
        ]
      }
    ]
  }
}"""
)
