const en = {
  open: "Quality and approved knowledge",
  loading: "Loading saved versions…",
  retry: "Retry",
  failed:
    "Could not load or save this configuration. Your draft is still here.",
  history: "Version history",
  restore: "Load this version as a new draft",
  published: "Published",
  draft: "Draft",
  testRequired:
    "Save → deterministic test → publish. Then create and publish a connected flow using this agent version. Existing flows and calls keep their pinned version.",
  instructions: "Agent instructions",
  language: "Conversation language",
  grammar: "Agent first-person grammar",
  caller: "Default caller address",
  unknown: "Unknown / natural neutral phrasing",
  feminine: "Feminine",
  masculine: "Masculine",
  neutral: "Neutral",
  voice: "Voice identifier (empty keeps existing voice)",
  pace: "Speaking pace",
  style: "Speaking style",
  concise: "Concise",
  balanced: "Balanced",
  detailed: "Detailed",
  fallback: "When information is missing",
  clarify: "Ask a clarification",
  handoff: "Offer human assistance",
  tokens: "Maximum response tokens",
  seconds: "Maximum session seconds",
  vocabulary: "STT vocabulary (one term per line)",
  dictionary: "Pronunciation dictionary",
  original: "Original spelling",
  spoken: "Approved spoken form",
  context: "Required context phrase (optional)",
  cases: "Pronunciation test cases (one per line)",
  add: "Add entry",
  remove: "Remove",
  save: "Save new draft",
  publish: "Publish tested version",
  saved: "Saved. Run the deterministic test before publishing.",
  tools: "Existing permitted tools",
  noTools:
    "No business-action tools are enabled. This editor does not grant new tool capabilities.",
  knowledge: "Approved business knowledge",
  noKnowledge:
    "No knowledge versions yet. Create and publish a source, then select it for this agent.",
  select: "Include source",
  revoked: "Revoked",
  stale: "Expired or not yet valid",
  newSource: "New knowledge source",
  revision: "New version",
  title: "Document title",
  content: "Source content",
  key: "Stable fact key",
  statement: "Approved complete statement",
  addFact: "Add statement",
  factsHint:
    "Use the same stable key for the same business subject. Conflicting values prevent publication. Statements are approved business information, never evidence that a payment, booking or message succeeded.",
  from: "Valid from (UTC)",
  until: "Valid until (UTC, optional)",
  saveKnowledge: "Save knowledge draft",
  publishKnowledge: "Publish knowledge",
  revoke: "Revoke source access",
  clear: "Start a new source",
  evaluate: "Deterministic evaluation",
  disclaimer:
    "This test checks saved configuration and exact approved statements. It does not call an LLM, recognize speech, synthesize audio, execute tools, or place calls.",
  scenario: "Typed scenario",
  fact: "Optional exact fact key to inspect",
  run: "Run deterministic test",
  response: "Rendered response",
  accepted: "Accepted typed text (no STT)",
  evidence: "Eligible evidence",
  conflicts: "Conflicting fact keys",
  stages:
    "STT / LLM / TTS: not run. Provider cost: 0. Handoff: not requested. Tools and receipts: none.",
  timing: "Deterministic validation time",
  noEvidence: "No eligible source",
  invalid:
    "Unavailable or conflicting knowledge must be resolved before publication.",
  voiceStatus: "Live voice calls",
  voiceNone:
    "No published voice flow uses this agent. New voice calls will not use these instructions until a connected flow is published.",
  voiceUses:
    "New calls use v{agent} through the flow “{flow}” (flow v{flowVersion}).",
  voiceNotCallable:
    "This binding cannot start new calls: the bound agent version or flow version is unpublished or invalid.",
  voiceBehind:
    "v{latest} is published, but voice calls still use v{agent}. To apply it to new calls, publish a flow version that uses v{latest}. Calls already in progress keep their version.",
  liveVoice: "live voice",
} as const;
const he: Record<keyof typeof en, string> = {
  open: "איכות שיחה וידע מאושר",
  loading: "טוען גרסאות שמורות…",
  retry: "ניסיון נוסף",
  failed: "לא ניתן לטעון או לשמור את ההגדרות. הטיוטה נשמרה במסך.",
  history: "היסטוריית גרסאות",
  restore: "טעינת הגרסה כטיוטה חדשה",
  published: "פורסם",
  draft: "טיוטה",
  testRequired:
    "שמירה ← בדיקה דטרמיניסטית ← פרסום. לאחר מכן יש ליצור ולפרסם תהליך מקושר עם גרסת הסוכן החדשה. תהליכים ושיחות קיימים ממשיכים עם הגרסה שנקבעה עבורם.",
  instructions: "הנחיות הסוכן",
  language: "שפת השיחה",
  grammar: "לשון הסוכן בגוף ראשון",
  caller: "ברירת מחדל לפנייה למתקשר",
  unknown: "לא ידוע / ניסוח ניטרלי טבעי",
  feminine: "נקבה",
  masculine: "זכר",
  neutral: "ניטרלי",
  voice: "מזהה קול (ריק משאיר את הקול הקיים)",
  pace: "קצב הדיבור",
  style: "סגנון הדיבור",
  concise: "תמציתי",
  balanced: "מאוזן",
  detailed: "מפורט",
  fallback: "כאשר חסר מידע",
  clarify: "שאלת הבהרה",
  handoff: "הצעת עזרה אנושית",
  tokens: "מגבלת טוקנים לתשובה",
  seconds: "משך שיחה מרבי בשניות",
  vocabulary: "אוצר מילים לתמלול (מונח בכל שורה)",
  dictionary: "מילון הגייה",
  original: "כתיב מקורי",
  spoken: "הגייה מאושרת",
  context: "ביטוי הקשר נדרש (לא חובה)",
  cases: "דוגמאות לבדיקת הגייה (דוגמה בכל שורה)",
  add: "הוספת ערך",
  remove: "הסרה",
  save: "שמירת טיוטה חדשה",
  publish: "פרסום גרסה שנבדקה",
  saved: "נשמר. יש להריץ בדיקה דטרמיניסטית לפני פרסום.",
  tools: "כלים מורשים קיימים",
  noTools: "לא הופעלו כלי פעולות עסקיות. מסך זה אינו מעניק יכולות חדשות לכלים.",
  knowledge: "ידע עסקי מאושר",
  noKnowledge:
    "עדיין אין גרסאות ידע. יש ליצור ולפרסם מקור, ואז לבחור אותו לסוכן.",
  select: "שימוש במקור",
  revoked: "הגישה בוטלה",
  stale: "פג תוקף או שטרם נכנס לתוקף",
  newSource: "מקור ידע חדש",
  revision: "גרסה חדשה",
  title: "כותרת המסמך",
  content: "תוכן המקור",
  key: "מפתח עובדה קבוע",
  statement: "משפט מלא ומאושר",
  addFact: "הוספת משפט",
  factsHint:
    "יש להשתמש באותו מפתח לאותו נושא עסקי. ערכים סותרים מונעים פרסום. משפטים הם מידע עסקי מאושר, ולעולם אינם הוכחה לכך שתשלום, הזמנה או הודעה בוצעו.",
  from: "בתוקף מתאריך (UTC)",
  until: "בתוקף עד (UTC, לא חובה)",
  saveKnowledge: "שמירת טיוטת ידע",
  publishKnowledge: "פרסום ידע",
  revoke: "ביטול הגישה למקור",
  clear: "יצירת מקור חדש",
  evaluate: "בדיקה דטרמיניסטית",
  disclaimer:
    "הבדיקה בוחנת הגדרות שמורות ומשפטים מאושרים מדויקים. היא אינה מפעילה מודל שפה, זיהוי דיבור, סינתזת קול, כלים או שיחות טלפון.",
  scenario: "תרחיש מוקלד",
  fact: "מפתח עובדה מדויק לבדיקה (לא חובה)",
  run: "הרצת בדיקה דטרמיניסטית",
  response: "התשובה שהורכבה",
  accepted: "טקסט מוקלד שהתקבל (ללא תמלול)",
  evidence: "מקורות מידע תקפים",
  conflicts: "מפתחות עובדה סותרים",
  stages:
    "תמלול / מודל / סינתזה: לא הופעלו. עלות ספק: 0. העברה לאדם: לא התבקשה. כלים ואישורי ביצוע: אין.",
  timing: "משך האימות הדטרמיניסטי",
  noEvidence: "אין מקור תקף",
  invalid: "יש לפתור ידע חסר או סותר לפני הפרסום.",
  voiceStatus: "שיחות קוליות פעילות",
  voiceNone:
    "אין תהליך קולי מפורסם שמשתמש בסוכן הזה. שיחות קוליות חדשות לא ישתמשו בהנחיות האלה עד שיפורסם תהליך מקושר.",
  voiceUses:
    "שיחות חדשות משתמשות בגרסה v{agent} דרך התהליך „{flow}” (גרסת תהליך v{flowVersion}).",
  voiceNotCallable:
    "הקישור הזה לא יכול להתחיל שיחות חדשות: גרסת הסוכן או גרסת התהליך המקושרת אינה מפורסמת או אינה תקינה.",
  voiceBehind:
    "גרסה v{latest} פורסמה, אבל שיחות קוליות עדיין משתמשות בגרסה v{agent}. כדי להחיל אותה על שיחות חדשות, יש לפרסם גרסת תהליך שמשתמשת ב-v{latest}. שיחות שכבר מתנהלות ממשיכות עם הגרסה שלהן.",
  liveVoice: "בשיחות קוליות",
};
export function qualityCopy(locale: string): Record<keyof typeof en, string> {
  return locale.startsWith("he") ? he : en;
}
