# Generated by scripts/generate_runtime_policy.py.
import json

MODEL_RATES = json.loads(r"""{
  "gemini-3.5-flash-lite": {
    "reasoningEffort": "minimal",
    "sampling": false,
    "inputUsdPerMillion": 0.3,
    "cachedInputUsdPerMillion": 0.03,
    "outputUsdPerMillion": 2.5
  },
  "gemini-3.1-flash-lite": {
    "reasoningEffort": "minimal",
    "sampling": true,
    "inputUsdPerMillion": 0.25,
    "cachedInputUsdPerMillion": 0.025,
    "audioInputUsdPerMillion": 0.5,
    "cachedAudioInputUsdPerMillion": 0.05,
    "outputUsdPerMillion": 1.5
  }
}""")
