"""Generate shared runtime policy without provider traffic; --check detects drift."""

import argparse
import json
import shutil
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    data = json.loads(
        (ROOT / "db/contracts/agent-runtime-policy.v1.json").read_text(encoding="utf-8")
    )
    body = json.dumps(data, ensure_ascii=False, indent=2)
    outputs = {
        "packages/ts/config/src/runtime-policy.generated.ts": (
            "// Generated by scripts/generate_runtime_policy.py.\n"
            f"export const agentRuntimePolicy = {body} as const;\n"
        ),
        "packages/py/oron-agent/src/oron_agent/runtime_policy.py": (
            "# Generated by scripts/generate_runtime_policy.py.\nimport json\n\n"
            f'RUNTIME_POLICY = json.loads(r"""{body}""")\nVOICE_POLICY = RUNTIME_POLICY["voice"]\n'
        ),
    }
    outputs["packages/py/oron-common/src/oron_common/model_rates.py"] = (
        "# Generated by scripts/generate_runtime_policy.py.\nimport json\n\n"
        + 'MODEL_RATES = json.loads(r"""'
        + json.dumps(data["models"], indent=2)
        + '""")\n'
    )
    stale = []
    for name, content in outputs.items():
        path = ROOT / name
        if name.endswith(".ts"):
            formatter = shutil.which("pnpm")
            if formatter is None:
                raise RuntimeError("pnpm is required to format the generated TypeScript")
            content = subprocess.run(  # noqa: S603 -- fixed repository formatter
                [formatter, "exec", "prettier", "--stdin-filepath", str(path)],
                input=content,
                capture_output=True,
                text=True,
                encoding="utf-8",
                cwd=ROOT,
                check=True,
            ).stdout
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            stale.append(name)
            if not args.check:
                path.write_text(content, encoding="utf-8", newline="\n")
    if args.check and stale:
        print("Stale runtime policy: " + ", ".join(stale))
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
