"""Mirror the canonical service agent scope policy into its TypeScript and Python consumers.

``db/contracts/service-agent-policy.v1.json`` is the only authored copy. Voice (Python)
and WhatsApp/web (TypeScript) each import a generated mirror so neither runtime
reads a repository path at run time, and ``--check`` fails when a mirror drifts.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CANONICAL = ROOT / "db" / "contracts" / "service-agent-policy.v1.json"
TYPESCRIPT = ROOT / "packages" / "ts" / "crm" / "src" / "agent-scope-policy.generated.ts"
PYTHON = ROOT / "packages" / "py" / "oron-agent" / "src" / "oron_agent" / "scope_policy_contract.py"

_HEADER = (
    "Generated by scripts/generate_agent_policy.py from "
    "db/contracts/service-agent-policy.v1.json. Do not edit."
)


_INVISIBLE = re.compile("[\u00ad\u200b-\u200f\u202a-\u202e\u2066-\u2069\ufeff]")


def _visible(source: str) -> str:
    """Escape zero-width and bidi controls so no mirror hides characters in source."""

    return _INVISIBLE.sub(lambda match: f"\\u{ord(match.group()):04x}", source)


def _canonical() -> dict:
    return json.loads(CANONICAL.read_text(encoding="utf-8"))


def _typescript(contract: dict) -> str:
    body = _visible(json.dumps(contract, ensure_ascii=False, indent=2))
    source = f"// {_HEADER}\n\nexport const serviceAgentPolicy = {body} as const;\n"
    prettier = shutil.which("pnpm")
    if prettier is None:
        raise RuntimeError("pnpm is required to format the TypeScript agent policy mirror")
    formatted = subprocess.run(  # noqa: S603 - fixed argv, repository-local formatter
        [prettier, "exec", "prettier", "--stdin-filepath", str(TYPESCRIPT)],
        input=source,
        capture_output=True,
        check=True,
        cwd=ROOT,
        encoding="utf-8",
    )
    return formatted.stdout


def _python(contract: dict) -> str:
    body = _visible(json.dumps(contract, ensure_ascii=False, indent=2))
    if '"""' in body:
        raise RuntimeError("agent policy cannot be embedded in a triple-quoted string")
    return (
        f'"""{_HEADER}"""\n\n'
        "import json\n"
        "from typing import Any, Final\n\n"
        f'POLICY: Final[dict[str, Any]] = json.loads(\n    r"""{body}"""\n)\n'
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if a mirror is stale")
    arguments = parser.parse_args()
    contract = _canonical()
    expected = {TYPESCRIPT: _typescript(contract), PYTHON: _python(contract)}
    stale = [
        path
        for path, content in expected.items()
        if not path.exists() or path.read_text(encoding="utf-8") != content
    ]
    if arguments.check:
        for path in stale:
            print(f"stale agent policy mirror: {path.relative_to(ROOT)}", file=sys.stderr)
        return 1 if stale else 0
    for path in stale:
        path.write_text(expected[path], encoding="utf-8", newline="\n")
        print(f"wrote {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
