"""Mirror the canonical lead capture contract into its TypeScript and Python consumers.

``db/contracts/lead-capture.v1.json`` is the only authored copy. Voice (Python)
and WhatsApp/web (TypeScript) each import a generated mirror so neither runtime
reads a repository path at run time, and ``--check`` fails when a mirror drifts.
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CANONICAL = ROOT / "db" / "contracts" / "lead-capture.v1.json"
TYPESCRIPT = ROOT / "packages" / "ts" / "crm" / "src" / "lead-capture-contract.generated.ts"
PYTHON = ROOT / "packages" / "py" / "oron-agent" / "src" / "oron_agent" / "lead_capture_contract.py"

_HEADER = (
    "Generated by scripts/generate_lead_contract.py from "
    "db/contracts/lead-capture.v1.json. Do not edit."
)


def _canonical() -> dict:
    return json.loads(CANONICAL.read_text(encoding="utf-8"))


def _typescript(contract: dict) -> str:
    body = json.dumps(contract, ensure_ascii=False, indent=2)
    source = f"// {_HEADER}\n\nexport const leadCaptureContract = {body} as const;\n"
    prettier = shutil.which("pnpm")
    if prettier is None:
        raise RuntimeError("pnpm is required to format the TypeScript lead contract mirror")
    formatted = subprocess.run(  # noqa: S603 - fixed argv, repository-local formatter
        [prettier, "exec", "prettier", "--stdin-filepath", str(TYPESCRIPT)],
        input=source,
        capture_output=True,
        check=True,
        cwd=ROOT,
        encoding="utf-8",
    )
    return formatted.stdout


def _python(contract: dict) -> str:
    body = json.dumps(contract, ensure_ascii=False, indent=2)
    if '"""' in body:
        raise RuntimeError("lead contract cannot be embedded in a triple-quoted string")
    return (
        f'"""{_HEADER}"""\n\n'
        "import json\n"
        "from typing import Any, Final\n\n"
        f'CONTRACT: Final[dict[str, Any]] = json.loads(\n    r"""{body}"""\n)\n'
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if a mirror is stale")
    arguments = parser.parse_args()
    contract = _canonical()
    expected = {TYPESCRIPT: _typescript(contract), PYTHON: _python(contract)}
    stale = [
        path
        for path, content in expected.items()
        if not path.exists() or path.read_text(encoding="utf-8") != content
    ]
    if arguments.check:
        for path in stale:
            print(f"stale lead contract mirror: {path.relative_to(ROOT)}", file=sys.stderr)
        return 1 if stale else 0
    for path in stale:
        path.write_text(expected[path], encoding="utf-8", newline="\n")
        print(f"wrote {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
